name: Neues Treffen vorschlagen
description: Schlage ein neues Fediverse-Treffen vor.
title: "[Neues Treffen] "
labels: ["neues treffen"]
assignees: []
body:
  - type: input
    id: hashtag
    attributes:
      label: Hashtag
      description: z. B. #feditreffberlin
      placeholder: "#feditreffberlin"
    validations:
      required: true
  - type: input
    id: ort
    attributes:
      label: Ort / Adresse
      description: Stadt oder vollständige Adresse (Koordinaten werden automatisch ermittelt)
      placeholder: "Berlin oder Berlin, Alexanderplatz 1"
    validations:
      required: true
  - type: input
    id: lat
    attributes:
      label: Breitengrad (optional)
      description: Falls bekannt, kann die genaue Koordinate angegeben werden. Wird sonst automatisch ermittelt.
      placeholder: "52.5200"
    validations:
      required: false
  - type: input
    id: lng
    attributes:
      label: Längengrad (optional)
      description: Falls bekannt, kann die genaue Koordinate angegeben werden. Wird sonst automatisch ermittelt.
      placeholder: "13.4050"
    validations:
      required: false
  - type: textarea
    id: beschreibung
    attributes:
      label: Beschreibung
      description: Kurze Beschreibung oder Link zum Mastodon-Post
      placeholder: "Monatliches Treffen im Café XY"
    validations:
      required: false
